trigger:
- main

pool:
  vmImage: windows-latest

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'  # Select only one Python version
  displayName: 'Use Python 3.9'

- script: |
    python -m pip install --upgrade pip
    pip install numpy==1.21.0 -r requirements.txt pyinstaller
  displayName: 'Install dependencies and PyInstaller'

- script: |
    pyinstaller --windowed gui.py
  displayName: 'Build Windows executable'

- script: |
    pytest
  displayName: 'Run tests'
