trigger:
- main

pool:
  vmImage: windows-latest

strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install numpy==1.21.0  # Specify the version of numpy
    pip install -r requirements.txt
    pip install pyinstaller
  displayName: 'Install dependencies and PyInstaller with downgraded numpy'

- script: |
    pyinstaller --windowed gui.py
  displayName: 'Build Windows executable'

- script: |
    pytest
  displayName: 'Run tests'
